### ISSUE TITLE
[Chore] Recruit 페이지 breakpoint

### ISSUE THREAD

**Issue by GraceKim527** [9oormthon-univ/9oormthon_univ#13]
## 🛠 Issue

리크루트 페이지의 xxl, xl, lg, md, sm, xs 화면을 구현합니다.

## 📝 To-do

- [x] gds와 rem값 컨벤션으로 변경합니다.
- [x] 자주 묻는 질문 부분을 구현합니다.
- [x] 리크루트 페이지가 수정됨에 따라 다시 화면을 구현합니다.
- [x] 리크루트 페이지의 브레이크포인트를 구현합니다.
