### ISSUE TITLE
[Feat] 3기 데이터 추가 및 각종 수정 사항

### ISSUE THREAD

**Issue by GraceKim527** [9oormthon-univ/9oormthon_univ#44]
## 🛠 Issue

3기 데이터를 추가하고 프로젝트 페이지에 업데이트합니다.

## 📝 To-do

- [x] 3기 데이터 Constants 추가
- [x] 프로젝트 페이지에 3기 데이터 추가
- [x] 배포 안된 팀의 경우 팀 페이지 들어가지지 않도록 수정 필요
- [x] 모바일 환경에서 프론트엔드, 백엔드 블럭 깨지는 현상 수정 필요
- [x] 프론트엔드, 백엔드 깃허브 링크가 안보일 때 클릭되는 현상 수정 필요
- [x] 프로젝트 설명란 글자수 제한 85자로 변경
